name: Deploy Lambda and API Gateway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Zip Lambda function
      run: zip lambda_function.zip src/main.py

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform configuration
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}